import React from 'react';
import { 
  Search, Grid3X3, List, ArrowRight, Star, TrendingUp, Crown,
  Calculator, Clock, Users, Target, Flame, Sparkles, Timer,
  Filter, SortAsc, BarChart3, Eye, Award, Zap, Shield,
  CheckCircle2, Lightbulb, Workflow, MapPin, Compass, Radar,
  Crosshair, Fingerprint, RefreshCw, Shuffle, ListFilter,
  Heart, Code, Globe, Settings, FileText, Video, Brain,
  Download, Image, Music, Share2
} from 'lucide-react';

export interface Calculator {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  featured?: boolean;
  function?: string;
  isNew?: boolean;
  isPro?: boolean;
  isPopular?: boolean;
  difficulty?: 'easy' | 'medium' | 'advanced';
  usageCount?: number;
  rating?: number;
  tags?: string[];
  longDescription?: string;
  features?: string[];
  inputTypes?: string[];
  outputTypes?: string[];
  estimatedTime?: string;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  gradient: string;
  calculators: Calculator[];
  isPopular?: boolean;
  totalTools?: number;
  trending?: boolean;
  iconComponent?: React.ReactNode;
}

const iconMap = {
  'fa-chart-line': BarChart3,
  'fa-heartbeat': Heart,
  'fa-square-root-alt': Calculator,
  'fa-calendar-day': Clock,
  'fa-exchange-alt': RefreshCw,
  'fa-file-alt': FileText,
  'fa-video': Video,
  'fa-bitcoin': Target,
  'fa-code': Code,
  'fa-robot': Brain,
  'fa-language': Globe,
  'fa-tools': Settings,
  'fa-piggy-bank': Target,
  'fa-percentage': Target,
  'fa-home': Target,
  'fa-chart-area': BarChart3,
  'fa-balance-scale': Target,
  'fa-weight': Target,
  'fa-fire': Flame,
  'fa-birthday-cake': Timer,
  'fa-calculator': Calculator,
  'fa-percent': Target,
  'fa-receipt': FileText,
  'fa-key': Shield,
  'fa-chart-pie': BarChart3,
  'fa-file-invoice-dollar': FileText,
  'fa-youtube': Video,
  'fa-instagram': Image,
  'fa-facebook': Globe,
  'fa-twitter': Globe,
  'fa-soundcloud': Music,
  'fa-pinterest': Image,
  'fa-download': Download,
  'fa-hashtag': Target,
  'fa-link': Globe,
  'fa-share-alt': Share2
};

export const calculators: Calculator[] = [
  // Finance & Investment (8 tools)
  { 
    id: 'emi', 
    name: 'EMI Calculator', 
    description: 'Calculate EMI for loans with detailed breakdown', 
    category: 'finance', 
    icon: 'fa-chart-line', 
    featured: true, 
    isPopular: true,
    difficulty: 'easy',
    rating: 4.8,
    usageCount: 125000,
    tags: ['loan', 'emi', 'finance'],
    longDescription: 'Calculate your Equated Monthly Installment (EMI) with detailed amortization schedule, interest breakdown, and payment analysis.',
    features: ['Amortization Schedule', 'Interest Breakdown', 'Payment Analysis', 'Prepayment Options'],
    inputTypes: ['Principal Amount', 'Interest Rate', 'Loan Tenure'],
    outputTypes: ['Monthly EMI', 'Total Interest', 'Total Payment'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'sip', 
    name: 'SIP Calculator', 
    description: 'Systematic Investment Planning with growth projections', 
    category: 'finance', 
    icon: 'fa-piggy-bank', 
    featured: true, 
    isPopular: true,
    difficulty: 'easy',
    rating: 4.7,
    usageCount: 98000,
    tags: ['sip', 'investment', 'mutual funds'],
    longDescription: 'Plan your systematic investment with detailed projections, goal planning, and wealth accumulation analysis.',
    features: ['Goal Planning', 'Growth Projections', 'Inflation Adjustment', 'Step-up SIP'],
    inputTypes: ['Monthly Investment', 'Expected Returns', 'Time Period'],
    outputTypes: ['Maturity Amount', 'Total Investment', 'Wealth Gained'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'compound-interest', 
    name: 'Compound Interest', 
    description: 'Interest calculation with compounding frequency', 
    category: 'finance', 
    icon: 'fa-percentage', 
    featured: true, 
    isPopular: true,
    difficulty: 'medium',
    rating: 4.6,
    usageCount: 87000,
    tags: ['compound', 'interest', 'investment'],
    longDescription: 'Calculate compound interest with various compounding frequencies and visualize growth over time.',
    features: ['Multiple Compounding Frequencies', 'Growth Visualization', 'Year-by-Year Breakdown'],
    inputTypes: ['Principal', 'Annual Rate', 'Time Period', 'Compounding Frequency'],
    outputTypes: ['Final Amount', 'Interest Earned', 'Growth Chart'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'mortgage', 
    name: 'Mortgage Calculator', 
    description: 'Complete home loan analysis with taxes and insurance', 
    category: 'finance', 
    icon: 'fa-home', 
    featured: true, 
    isPopular: true,
    difficulty: 'medium',
    rating: 4.5,
    usageCount: 76000,
    tags: ['mortgage', 'home loan', 'property'],
    longDescription: 'Comprehensive mortgage calculator with property taxes, insurance, and PMI calculations.',
    features: ['Property Tax Calculation', 'Insurance Estimates', 'PMI Analysis', 'Extra Payment Impact'],
    inputTypes: ['Home Price', 'Down Payment', 'Interest Rate', 'Loan Term'],
    outputTypes: ['Monthly Payment', 'Total Interest', 'Amortization Schedule'],
    estimatedTime: '2-3 minutes'
  },
  { 
    id: 'investment', 
    name: 'Investment Calculator', 
    description: 'Advanced investment planning and portfolio analysis', 
    category: 'finance', 
    icon: 'fa-chart-area', 
    featured: true, 
    isPro: true,
    difficulty: 'advanced',
    rating: 4.4,
    usageCount: 54000,
    tags: ['investment', 'portfolio', 'returns'],
    longDescription: 'Advanced investment calculator with portfolio diversification, risk analysis, and return projections.',
    features: ['Portfolio Diversification', 'Risk Analysis', 'Return Projections', 'Asset Allocation'],
    inputTypes: ['Investment Amount', 'Asset Mix', 'Risk Profile', 'Time Horizon'],
    outputTypes: ['Expected Returns', 'Risk Metrics', 'Portfolio Performance'],
    estimatedTime: '3-5 minutes'
  },
  { 
    id: 'loan-comparison', 
    name: 'Loan Comparison', 
    description: 'Compare multiple loan offers side by side', 
    category: 'finance', 
    icon: 'fa-balance-scale', 
    featured: true,
    difficulty: 'medium',
    rating: 4.3,
    usageCount: 45000,
    tags: ['loan', 'comparison', 'finance'],
    longDescription: 'Compare multiple loan offers with detailed analysis of terms, costs, and benefits.',
    features: ['Side-by-Side Comparison', 'Cost Analysis', 'Benefits Breakdown', 'Recommendation Engine'],
    inputTypes: ['Multiple Loan Offers', 'Terms & Conditions', 'Interest Rates'],
    outputTypes: ['Comparison Table', 'Cost Analysis', 'Best Option Recommendation'],
    estimatedTime: '2-3 minutes'
  },
  { 
    id: 'retirement-planning', 
    name: 'Retirement Planning', 
    description: 'Comprehensive retirement savings calculator', 
    category: 'finance', 
    icon: 'fa-chart-pie', 
    isNew: true,
    isPro: true,
    difficulty: 'advanced',
    rating: 4.9,
    usageCount: 32000,
    tags: ['retirement', 'savings', 'planning'],
    longDescription: 'Plan your retirement with detailed savings projections, inflation adjustments, and goal tracking.',
    features: ['Inflation Adjustment', 'Goal Tracking', 'Savings Projections', 'Withdrawal Strategy'],
    inputTypes: ['Current Age', 'Retirement Age', 'Current Savings', 'Monthly Contributions'],
    outputTypes: ['Retirement Corpus', 'Monthly Savings Required', 'Withdrawal Plan'],
    estimatedTime: '5-7 minutes'
  },
  { 
    id: 'tax-calculator', 
    name: 'Tax Calculator', 
    description: 'Income tax calculation with deductions', 
    category: 'finance', 
    icon: 'fa-file-invoice-dollar', 
    isNew: true,
    difficulty: 'medium',
    rating: 4.2,
    usageCount: 28000,
    tags: ['tax', 'income', 'deductions'],
    longDescription: 'Calculate income tax with various deductions, exemptions, and tax-saving options.',
    features: ['Multiple Tax Regimes', 'Deduction Calculator', 'Tax Planning', 'Refund Calculator'],
    inputTypes: ['Annual Income', 'Deductions', 'Investments', 'Tax Regime'],
    outputTypes: ['Tax Liability', 'Take-home Salary', 'Tax Savings'],
    estimatedTime: '3-4 minutes'
  },

  // Health & Fitness (3 tools)
  { 
    id: 'bmi', 
    name: 'BMI Calculator', 
    description: 'Body mass index calculator', 
    category: 'health', 
    icon: 'fa-weight', 
    featured: true,
    difficulty: 'easy',
    rating: 4.6,
    usageCount: 89000,
    tags: ['bmi', 'health', 'fitness'],
    longDescription: 'Calculate your Body Mass Index with health recommendations and category analysis.',
    features: ['BMI Calculation', 'Health Category', 'Recommendations', 'Ideal Weight Range'],
    inputTypes: ['Height', 'Weight', 'Age'],
    outputTypes: ['BMI Value', 'Health Category', 'Recommendations'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'bmr', 
    name: 'BMR Calculator', 
    description: 'Metabolic rate calculator', 
    category: 'health', 
    icon: 'fa-fire', 
    featured: true,
    difficulty: 'easy',
    rating: 4.5,
    usageCount: 67000,
    tags: ['bmr', 'metabolism', 'calories'],
    longDescription: 'Calculate your Basal Metabolic Rate and daily calorie requirements for different activity levels.',
    features: ['BMR Calculation', 'Activity Level Adjustment', 'Calorie Requirements', 'Weight Goals'],
    inputTypes: ['Age', 'Gender', 'Height', 'Weight', 'Activity Level'],
    outputTypes: ['BMR Value', 'Daily Calories', 'Goal Calories'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'age', 
    name: 'Age Calculator', 
    description: 'Calculate exact age', 
    category: 'health', 
    icon: 'fa-birthday-cake', 
    featured: true,
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 45000,
    tags: ['age', 'date', 'calculator'],
    longDescription: 'Calculate exact age in years, months, days, hours, and minutes with additional date calculations.',
    features: ['Exact Age Calculation', 'Age in Different Units', 'Next Birthday', 'Age Comparison'],
    inputTypes: ['Birth Date', 'Current Date'],
    outputTypes: ['Exact Age', 'Days Lived', 'Next Birthday'],
    estimatedTime: '< 1 minute'
  },

  // Math & Numbers (15+ tools)
  { 
    id: 'scientific', 
    name: 'Scientific Calculator', 
    description: 'Advanced mathematical functions', 
    category: 'math', 
    icon: 'fa-calculator', 
    featured: true,
    difficulty: 'medium',
    rating: 4.7,
    usageCount: 112000,
    tags: ['scientific', 'math', 'calculator'],
    longDescription: 'Full-featured scientific calculator with trigonometric, logarithmic, and advanced mathematical functions.',
    features: ['Scientific Functions', 'Memory Operations', 'History', 'Unit Conversion'],
    inputTypes: ['Mathematical Expressions', 'Numbers', 'Functions'],
    outputTypes: ['Calculation Results', 'Step-by-step Solutions'],
    estimatedTime: 'Variable'
  },
  { 
    id: 'percentage', 
    name: 'Percentage Calculator', 
    description: 'Calculate percentages', 
    category: 'math', 
    icon: 'fa-percent', 
    featured: true,
    difficulty: 'easy',
    rating: 4.6,
    usageCount: 134000,
    tags: ['percentage', 'math', 'calculator'],
    longDescription: 'Calculate percentages, percentage change, and percentage of a number with detailed explanations.',
    features: ['Percentage Calculation', 'Percentage Change', 'Percentage of Number', 'Discount Calculator'],
    inputTypes: ['Numbers', 'Percentage Values'],
    outputTypes: ['Percentage Results', 'Explanations'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'algebra-solver', 
    name: 'Algebra Solver', 
    description: 'Solve algebraic equations', 
    category: 'math', 
    icon: 'fa-calculator', 
    difficulty: 'medium',
    rating: 4.5,
    usageCount: 67000,
    tags: ['algebra', 'equations', 'math'],
    longDescription: 'Solve linear and quadratic equations with step-by-step solutions.',
    features: ['Linear Equations', 'Quadratic Equations', 'Step-by-step Solutions', 'Graph Plotting'],
    inputTypes: ['Algebraic Expressions', 'Equations'],
    outputTypes: ['Solutions', 'Graphs', 'Step-by-step Process'],
    estimatedTime: '1-2 minutes'
  },
  { 
    id: 'fraction-decimal', 
    name: 'Fraction ↔ Decimal', 
    description: 'Convert fractions and decimals', 
    category: 'math', 
    icon: 'fa-calculator', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 45000,
    tags: ['fraction', 'decimal', 'conversion'],
    longDescription: 'Convert between fractions and decimals with simplification and detailed explanations.',
    features: ['Fraction to Decimal', 'Decimal to Fraction', 'Simplification', 'Mixed Numbers'],
    inputTypes: ['Fractions', 'Decimals'],
    outputTypes: ['Converted Values', 'Simplified Forms'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'binary-decimal-hex', 
    name: 'Number Base Converter', 
    description: 'Binary, decimal, hex conversion', 
    category: 'math', 
    icon: 'fa-code', 
    difficulty: 'medium',
    rating: 4.4,
    usageCount: 38000,
    tags: ['binary', 'decimal', 'hex', 'conversion'],
    longDescription: 'Convert between binary, decimal, hexadecimal, and octal number systems.',
    features: ['Binary Conversion', 'Hex Conversion', 'Octal Support', 'Bit Operations'],
    inputTypes: ['Numbers in Any Base'],
    outputTypes: ['All Base Formats', 'Bit Representations'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'roman-decimal', 
    name: 'Roman ↔ Decimal', 
    description: 'Roman numeral conversion', 
    category: 'math', 
    icon: 'fa-calculator', 
    difficulty: 'easy',
    rating: 4.2,
    usageCount: 25000,
    tags: ['roman', 'decimal', 'numerals'],
    longDescription: 'Convert between Roman numerals and decimal numbers with validation.',
    features: ['Roman to Decimal', 'Decimal to Roman', 'Validation', 'Historical Context'],
    inputTypes: ['Roman Numerals', 'Decimal Numbers'],
    outputTypes: ['Converted Values', 'Validation Results'],
    estimatedTime: '< 1 minute'
  },

  // Daily Utilities (5+ tools)
  { 
    id: 'tip', 
    name: 'Tip Calculator', 
    description: 'Calculate tips and splits', 
    category: 'daily', 
    icon: 'fa-receipt', 
    featured: true,
    difficulty: 'easy',
    rating: 4.5,
    usageCount: 78000,
    tags: ['tip', 'bill', 'split'],
    longDescription: 'Calculate tips and split bills among multiple people with different tip percentages.',
    features: ['Tip Calculation', 'Bill Splitting', 'Custom Tip Rates', 'Per-person Breakdown'],
    inputTypes: ['Bill Amount', 'Tip Percentage', 'Number of People'],
    outputTypes: ['Tip Amount', 'Total Bill', 'Per Person Amount'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'password-generator', 
    name: 'Password Generator', 
    description: 'Generate secure passwords', 
    category: 'daily', 
    icon: 'fa-key', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 56000,
    tags: ['password', 'security', 'generator'],
    longDescription: 'Generate secure passwords with customizable length, character sets, and security requirements.',
    features: ['Customizable Length', 'Character Set Options', 'Security Strength', 'Multiple Passwords'],
    inputTypes: ['Length', 'Character Types', 'Exclude Similar'],
    outputTypes: ['Secure Password', 'Strength Analysis'],
    estimatedTime: '< 1 minute'
  },

  // Unit Converters (10+ tools)
  { 
    id: 'unit-converter', 
    name: 'Unit Converter', 
    description: 'Convert various units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    featured: true,
    difficulty: 'easy',
    rating: 4.6,
    usageCount: 89000,
    tags: ['units', 'conversion', 'measurement'],
    longDescription: 'Comprehensive unit converter for length, weight, temperature, and more.',
    features: ['Multiple Unit Types', 'Real-time Conversion', 'Precision Control', 'Favorites'],
    inputTypes: ['Values', 'Source Units', 'Target Units'],
    outputTypes: ['Converted Values', 'Conversion Rates'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'area-converter', 
    name: 'Area Converter', 
    description: 'Convert area units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 32000,
    tags: ['area', 'conversion', 'measurement'],
    longDescription: 'Convert between different area units including square meters, acres, hectares.',
    features: ['Multiple Area Units', 'Imperial & Metric', 'Real Estate Units', 'Precision Control'],
    inputTypes: ['Area Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Area', 'Comparison Chart'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'length-converter', 
    name: 'Length Converter', 
    description: 'Convert length units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.5,
    usageCount: 45000,
    tags: ['length', 'distance', 'conversion'],
    longDescription: 'Convert between different length units from millimeters to miles.',
    features: ['Multiple Length Units', 'Imperial & Metric', 'Scientific Units', 'Precision Control'],
    inputTypes: ['Length Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Length', 'Unit Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'weight-converter', 
    name: 'Weight Converter', 
    description: 'Convert weight units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 38000,
    tags: ['weight', 'mass', 'conversion'],
    longDescription: 'Convert between different weight and mass units.',
    features: ['Multiple Weight Units', 'Imperial & Metric', 'Scientific Units', 'Precision Control'],
    inputTypes: ['Weight Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Weight', 'Unit Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'temperature-converter', 
    name: 'Temperature Converter', 
    description: 'Convert temperature units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.6,
    usageCount: 56000,
    tags: ['temperature', 'celsius', 'fahrenheit'],
    longDescription: 'Convert between Celsius, Fahrenheit, Kelvin, and other temperature scales.',
    features: ['Multiple Temperature Scales', 'Scientific Scales', 'Weather Applications', 'Precision Control'],
    inputTypes: ['Temperature Value', 'Source Scale', 'Target Scale'],
    outputTypes: ['Converted Temperature', 'Scale Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'speed-converter', 
    name: 'Speed Converter', 
    description: 'Convert speed units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 28000,
    tags: ['speed', 'velocity', 'conversion'],
    longDescription: 'Convert between different speed and velocity units.',
    features: ['Multiple Speed Units', 'MPH to KPH', 'Scientific Units', 'Precision Control'],
    inputTypes: ['Speed Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Speed', 'Unit Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'volume-converter', 
    name: 'Volume Converter', 
    description: 'Convert volume units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 35000,
    tags: ['volume', 'capacity', 'conversion'],
    longDescription: 'Convert between different volume and capacity units.',
    features: ['Multiple Volume Units', 'Liquid & Dry Measures', 'Cooking Units', 'Precision Control'],
    inputTypes: ['Volume Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Volume', 'Unit Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'time-converter', 
    name: 'Time Converter', 
    description: 'Convert time units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 32000,
    tags: ['time', 'duration', 'conversion'],
    longDescription: 'Convert between different time units and durations.',
    features: ['Multiple Time Units', 'Duration Calculations', 'Scientific Units', 'Precision Control'],
    inputTypes: ['Time Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Time', 'Duration Breakdown'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'data-size-converter', 
    name: 'Data Size Converter', 
    description: 'Convert data size units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.5,
    usageCount: 42000,
    tags: ['data', 'storage', 'bytes'],
    longDescription: 'Convert between different data storage units from bytes to terabytes.',
    features: ['Binary & Decimal Units', 'Storage Calculations', 'Network Speeds', 'Precision Control'],
    inputTypes: ['Data Size', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Size', 'Storage Comparison'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'power-converter', 
    name: 'Power Converter', 
    description: 'Convert power units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.2,
    usageCount: 18000,
    tags: ['power', 'energy', 'watts'],
    longDescription: 'Convert between different power and energy units.',
    features: ['Multiple Power Units', 'Energy Calculations', 'Electrical Units', 'Precision Control'],
    inputTypes: ['Power Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Power', 'Energy Equivalents'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'pressure-converter', 
    name: 'Pressure Converter', 
    description: 'Convert pressure units', 
    category: 'unit-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.1,
    usageCount: 15000,
    tags: ['pressure', 'atmospheric', 'psi'],
    longDescription: 'Convert between different pressure units for engineering and science.',
    features: ['Multiple Pressure Units', 'Atmospheric Pressure', 'Scientific Units', 'Precision Control'],
    inputTypes: ['Pressure Value', 'Source Unit', 'Target Unit'],
    outputTypes: ['Converted Pressure', 'Unit Comparison'],
    estimatedTime: '< 1 minute'
  },

  // Currency & Crypto (4 tools)
  { 
    id: 'currency-converter', 
    name: 'Currency Converter', 
    description: 'Real-time currency conversion', 
    category: 'currency-crypto', 
    icon: 'fa-exchange-alt', 
    featured: true,
    difficulty: 'easy',
    rating: 4.7,
    usageCount: 156000,
    tags: ['currency', 'exchange', 'rates'],
    longDescription: 'Convert currencies with real-time exchange rates and historical data.',
    features: ['Real-time Rates', 'Historical Data', 'Rate Alerts', 'Multiple Currencies'],
    inputTypes: ['Amount', 'Source Currency', 'Target Currency'],
    outputTypes: ['Converted Amount', 'Exchange Rate', 'Rate History'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'crypto-converter', 
    name: 'Crypto Converter', 
    description: 'Convert cryptocurrencies', 
    category: 'currency-crypto', 
    icon: 'fa-bitcoin', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 89000,
    tags: ['crypto', 'bitcoin', 'ethereum'],
    longDescription: 'Convert between cryptocurrencies and fiat currencies with live market data.',
    features: ['Live Market Data', 'Multiple Cryptocurrencies', 'Price Charts', 'Market Analysis'],
    inputTypes: ['Amount', 'Source Crypto', 'Target Currency'],
    outputTypes: ['Converted Amount', 'Market Price', 'Price Charts'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'currency-history', 
    name: 'Currency History', 
    description: 'Historical exchange rates', 
    category: 'currency-crypto', 
    icon: 'fa-chart-line', 
    difficulty: 'medium',
    rating: 4.3,
    usageCount: 34000,
    tags: ['currency', 'history', 'rates'],
    longDescription: 'View historical exchange rates and currency trends with interactive charts.',
    features: ['Historical Data', 'Interactive Charts', 'Trend Analysis', 'Rate Comparison'],
    inputTypes: ['Currency Pair', 'Date Range', 'Chart Type'],
    outputTypes: ['Historical Rates', 'Charts', 'Trend Analysis'],
    estimatedTime: '1-2 minutes'
  },
  { 
    id: 'gold-silver-rates', 
    name: 'Gold & Silver Rates', 
    description: 'Precious metal rates', 
    category: 'currency-crypto', 
    icon: 'fa-chart-area', 
    difficulty: 'easy',
    rating: 4.2,
    usageCount: 28000,
    tags: ['gold', 'silver', 'precious metals'],
    longDescription: 'Track gold and silver prices with market analysis and trend data.',
    features: ['Live Metal Prices', 'Market Analysis', 'Price Charts', 'Investment Calculator'],
    inputTypes: ['Metal Type', 'Quantity', 'Date Range'],
    outputTypes: ['Current Prices', 'Value Calculation', 'Price Charts'],
    estimatedTime: '1-2 minutes'
  },

  // Text & Code Converters (15+ tools)
  { 
    id: 'base64-encoder-decoder', 
    name: 'Base64 Encoder/Decoder', 
    description: 'Encode and decode Base64', 
    category: 'text-converters', 
    icon: 'fa-code', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 67000,
    tags: ['base64', 'encode', 'decode'],
    longDescription: 'Encode and decode Base64 strings with support for text and binary data.',
    features: ['Text Encoding', 'Binary Support', 'URL Safe Base64', 'Validation'],
    inputTypes: ['Text', 'Binary Data'],
    outputTypes: ['Base64 String', 'Decoded Content'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'binary-text', 
    name: 'Binary ↔ Text', 
    description: 'Convert binary and text', 
    category: 'text-converters', 
    icon: 'fa-code', 
    difficulty: 'easy',
    rating: 4.2,
    usageCount: 45000,
    tags: ['binary', 'text', 'conversion'],
    longDescription: 'Convert between binary representation and text with various encoding options.',
    features: ['Multiple Encodings', 'ASCII Support', 'Unicode Support', 'Bit Grouping'],
    inputTypes: ['Text', 'Binary String'],
    outputTypes: ['Binary Code', 'Text Content'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'hash-generator', 
    name: 'Hash Generator', 
    description: 'Generate MD5, SHA hashes', 
    category: 'text-converters', 
    icon: 'fa-code', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 56000,
    tags: ['hash', 'md5', 'sha'],
    longDescription: 'Generate various hash algorithms including MD5, SHA-1, SHA-256, and more.',
    features: ['Multiple Algorithms', 'File Hashing', 'Hex/Base64 Output', 'Comparison Tool'],
    inputTypes: ['Text', 'Files'],
    outputTypes: ['Hash Values', 'Checksums'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'qr-code-generator', 
    name: 'QR Code Generator', 
    description: 'Generate QR codes', 
    category: 'text-converters', 
    icon: 'fa-qrcode', 
    difficulty: 'easy',
    rating: 4.6,
    usageCount: 89000,
    tags: ['qr', 'code', 'generator'],
    longDescription: 'Generate QR codes for text, URLs, contact info, and more with customization options.',
    features: ['Multiple Data Types', 'Size Customization', 'Color Options', 'Batch Generation'],
    inputTypes: ['Text', 'URLs', 'Contact Info'],
    outputTypes: ['QR Code Images', 'SVG Format'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'html-markdown', 
    name: 'HTML ↔ Markdown', 
    description: 'Convert HTML and Markdown', 
    category: 'text-converters', 
    icon: 'fa-code', 
    difficulty: 'medium',
    rating: 4.5,
    usageCount: 72000,
    tags: ['html', 'markdown', 'conversion'],
    longDescription: 'Convert between HTML and Markdown with formatting preservation and syntax highlighting.',
    features: ['Formatting Preservation', 'Syntax Highlighting', 'Table Support', 'Link Handling'],
    inputTypes: ['HTML Code', 'Markdown Text'],
    outputTypes: ['Converted Format', 'Preview'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'json-xml', 
    name: 'JSON ↔ XML', 
    description: 'Convert JSON and XML', 
    category: 'text-converters', 
    icon: 'fa-code', 
    difficulty: 'medium',
    rating: 4.4,
    usageCount: 58000,
    tags: ['json', 'xml', 'conversion'],
    longDescription: 'Convert between JSON and XML formats with structure validation and formatting.',
    features: ['Structure Validation', 'Formatting Options', 'Attribute Handling', 'Array Processing'],
    inputTypes: ['JSON Data', 'XML Data'],
    outputTypes: ['Converted Format', 'Validation Report'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'text-case-converter', 
    name: 'Text Case Converter', 
    description: 'Upper, lower, title case', 
    category: 'text-converters', 
    icon: 'fa-font', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 78000,
    tags: ['text', 'case', 'format'],
    longDescription: 'Convert text between different cases with smart formatting options.',
    features: ['Multiple Case Types', 'Smart Formatting', 'Batch Processing', 'Custom Rules'],
    inputTypes: ['Text Content'],
    outputTypes: ['Formatted Text', 'Multiple Formats'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'text-capitalizer', 
    name: 'Text Capitalizer', 
    description: 'Smart capitalization', 
    category: 'text-converters', 
    icon: 'fa-font', 
    difficulty: 'easy',
    rating: 4.2,
    usageCount: 45000,
    tags: ['text', 'capitalize', 'format'],
    longDescription: 'Intelligently capitalize text with grammar-aware formatting.',
    features: ['Grammar Rules', 'Title Formatting', 'Sentence Capitalization', 'Custom Rules'],
    inputTypes: ['Text Content'],
    outputTypes: ['Capitalized Text'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'text-reverser', 
    name: 'Text Reverser', 
    description: 'Reverse text strings', 
    category: 'text-converters', 
    icon: 'fa-exchange-alt', 
    difficulty: 'easy',
    rating: 4.1,
    usageCount: 32000,
    tags: ['text', 'reverse', 'format'],
    longDescription: 'Reverse text in various ways including character, word, and line reversal.',
    features: ['Character Reversal', 'Word Reversal', 'Line Reversal', 'Batch Processing'],
    inputTypes: ['Text Content'],
    outputTypes: ['Reversed Text'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'remove-duplicate-lines', 
    name: 'Remove Duplicate Lines', 
    description: 'Clean duplicate text', 
    category: 'text-converters', 
    icon: 'fa-filter', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 54000,
    tags: ['text', 'duplicate', 'clean'],
    longDescription: 'Remove duplicate lines from text with various comparison options.',
    features: ['Case Sensitivity Options', 'Whitespace Handling', 'Sort Options', 'Statistics'],
    inputTypes: ['Text with Duplicates'],
    outputTypes: ['Cleaned Text', 'Duplicate Report'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'slug-generator', 
    name: 'Slug Generator', 
    description: 'URL-friendly text', 
    category: 'text-converters', 
    icon: 'fa-link', 
    difficulty: 'easy',
    rating: 4.3,
    usageCount: 48000,
    tags: ['slug', 'url', 'seo'],
    longDescription: 'Generate SEO-friendly URL slugs from text with customization options.',
    features: ['SEO Optimization', 'Custom Separators', 'Character Limits', 'Unicode Handling'],
    inputTypes: ['Text Title'],
    outputTypes: ['URL Slug', 'SEO Analysis'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'sql-formatter', 
    name: 'SQL Formatter', 
    description: 'Format SQL queries', 
    category: 'text-converters', 
    icon: 'fa-database', 
    difficulty: 'medium',
    rating: 4.5,
    usageCount: 67000,
    tags: ['sql', 'format', 'database'],
    longDescription: 'Format and beautify SQL queries with syntax highlighting and validation.',
    features: ['Syntax Highlighting', 'Indentation Options', 'Keyword Formatting', 'Validation'],
    inputTypes: ['SQL Queries'],
    outputTypes: ['Formatted SQL', 'Syntax Report'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'regex-tester', 
    name: 'Regex Tester', 
    description: 'Test regular expressions', 
    category: 'text-converters', 
    icon: 'fa-search', 
    difficulty: 'advanced',
    rating: 4.6,
    usageCount: 76000,
    tags: ['regex', 'pattern', 'test'],
    longDescription: 'Test and debug regular expressions with match highlighting and explanation.',
    features: ['Match Highlighting', 'Pattern Explanation', 'Group Capture', 'Performance Analysis'],
    inputTypes: ['Regex Pattern', 'Test Text'],
    outputTypes: ['Match Results', 'Pattern Analysis'],
    estimatedTime: '1-2 minutes'
  },
  { 
    id: 'rot13-cipher', 
    name: 'ROT13 Cipher', 
    description: 'ROT13 encryption/decryption', 
    category: 'text-converters', 
    icon: 'fa-shield', 
    difficulty: 'easy',
    rating: 4.0,
    usageCount: 28000,
    tags: ['rot13', 'cipher', 'encryption'],
    longDescription: 'Encode and decode text using the ROT13 cipher algorithm.',
    features: ['ROT13 Encoding', 'Batch Processing', 'Character Preservation', 'Custom Rotations'],
    inputTypes: ['Text Content'],
    outputTypes: ['Encoded Text', 'Decoded Text'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'uuid-generator', 
    name: 'UUID Generator', 
    description: 'Generate unique identifiers', 
    category: 'text-converters', 
    icon: 'fa-fingerprint', 
    difficulty: 'easy',
    rating: 4.4,
    usageCount: 56000,
    tags: ['uuid', 'guid', 'identifier'],
    longDescription: 'Generate various types of UUIDs and GUIDs for application development.',
    features: ['Multiple UUID Versions', 'Bulk Generation', 'Validation', 'Format Options'],
    inputTypes: ['UUID Type', 'Quantity'],
    outputTypes: ['UUID List', 'Validation Status'],
    estimatedTime: '< 1 minute'
  },
  { 
    id: 'unicode-ascii', 
    name: 'Unicode ↔ ASCII', 
    description: 'Convert Unicode and ASCII', 
    category: 'text-converters', 
    icon: 'fa-font', 
    difficulty: 'medium',
    rating: 4.2,
    usageCount: 38000,
    tags: ['unicode', 'ascii', 'encoding'],
    longDescription: 'Convert between Unicode and ASCII with encoding options and character mapping.',
    features: ['Character Mapping', 'Encoding Options', 'Error Handling', 'Statistics'],
    inputTypes: ['Unicode Text', 'ASCII Text'],
    outputTypes: ['Converted Text', 'Character Report'],
    estimatedTime: '< 1 minute'
  }
];

export const categories: Category[] = [
  {
    id: 'finance',
    name: 'Finance & Investment',
    description: 'Professional financial calculators for smart money decisions',
    icon: 'fa-chart-line',
    color: 'green',
    gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
    calculators: calculators.filter(c => c.category === 'finance'),
    isPopular: true,
    trending: true
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    description: 'Health monitoring and fitness calculation tools',
    icon: 'fa-heartbeat',
    color: 'red',
    gradient: 'from-rose-500 via-pink-500 to-purple-600',
    calculators: calculators.filter(c => c.category === 'health'),
    isPopular: true,
    trending: false
  },
  {
    id: 'math',
    name: 'Math & Numbers',
    description: 'Advanced mathematical calculations and number systems',
    icon: 'fa-square-root-alt',
    color: 'blue',
    gradient: 'from-blue-500 via-indigo-500 to-purple-600',
    calculators: calculators.filter(c => c.category === 'math'),
    isPopular: true,
    trending: false
  },
  {
    id: 'daily',
    name: 'Daily Utilities',
    description: 'Everyday calculation tools and practical utilities',
    icon: 'fa-calendar-day',
    color: 'purple',
    gradient: 'from-purple-500 via-violet-500 to-pink-600',
    calculators: calculators.filter(c => c.category === 'daily'),
    isPopular: true,
    trending: false
  },
  {
    id: 'unit-converters',
    name: 'Unit Converters',
    description: 'Comprehensive unit conversion tools for all measurements',
    icon: 'fa-exchange-alt',
    color: 'orange',
    gradient: 'from-orange-500 via-amber-500 to-yellow-600',
    calculators: calculators.filter(c => c.category === 'unit-converters'),
    isPopular: true,
    trending: false
  },
  {
    id: 'file-converters',
    name: 'File Converters',
    description: 'Professional file format conversion and processing tools',
    icon: 'fa-file-alt',
    color: 'indigo',
    gradient: 'from-indigo-500 via-purple-500 to-pink-600',
    calculators: calculators.filter(c => c.category === 'file-converters'),
    isPopular: true,
    trending: true
  },
  {
    id: 'media-converters',
    name: 'Media Converters',
    description: 'Audio, video, and image format conversion tools',
    icon: 'fa-video',
    color: 'pink',
    gradient: 'from-pink-500 via-rose-500 to-red-600',
    calculators: calculators.filter(c => c.category === 'media-converters'),
    isPopular: true,
    trending: true
  },
  {
    id: 'currency-crypto',
    name: 'Currency & Crypto',
    description: 'Live currency rates and cryptocurrency conversion tools',
    icon: 'fa-bitcoin',
    color: 'yellow',
    gradient: 'from-yellow-500 via-orange-500 to-red-600',
    calculators: calculators.filter(c => c.category === 'currency-crypto'),
    isPopular: true,
    trending: false
  },
  {
    id: 'text-converters',
    name: 'Text & Code Tools',
    description: 'Text manipulation, formatting, and code processing tools',
    icon: 'fa-code',
    color: 'teal',
    gradient: 'from-teal-500 via-cyan-500 to-blue-600',
    calculators: calculators.filter(c => c.category === 'text-converters'),
    isPopular: true,
    trending: false
  },
  {
    id: 'ai-converters',
    name: 'AI-Powered Tools',
    description: 'Advanced AI tools for OCR, speech, and intelligent processing',
    icon: 'fa-robot',
    color: 'emerald',
    gradient: 'from-emerald-500 via-green-500 to-teal-600',
    calculators: calculators.filter(c => c.category === 'ai-converters'),
    isPopular: true,
    trending: true
  },
  {
    id: 'language-converters',
    name: 'Language & Script',
    description: 'Translation and script conversion tools',
    icon: 'fa-language',
    color: 'cyan',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-600',
    calculators: calculators.filter(c => c.category === 'language-converters'),
    isPopular: false,
    trending: false
  },
  {
    id: 'misc-converters',
    name: 'Specialized Tools',
    description: 'Unique and specialized conversion utilities',
    icon: 'fa-tools',
    color: 'gray',
    gradient: 'from-gray-500 via-slate-500 to-zinc-600',
    calculators: calculators.filter(c => c.category === 'misc-converters'),
    isPopular: false,
    trending: false
  },
   {
    id: 'downloader-tools',
    name: 'Downloader Tools',
    description: 'Tools for downloading content from various platforms',
    icon: 'fa-download',
    color: 'blue',
    gradient: 'from-blue-400 via-cyan-500 to-teal-500',
    calculators: calculators.filter(c => c.category === 'downloader-tools'),
    isPopular: false,
    trending: false
  },
  {
    id: 'social-media-tools',
    name: 'Social Media Tools',
    description: 'Tools to manage and enhance your social media presence',
    icon: 'fa-share-alt',
    color: 'purple',
    gradient: 'from-purple-400 via-pink-500 to-red-500',
    calculators: calculators.filter(c => c.category === 'social-media-tools'),
    isPopular: false,
    trending: false
  }
];

export const featuredCalculators = calculators.filter(c => c.featured);

export function getCalculatorById(id: string): Calculator | undefined {
  return calculators.find(calculator => calculator.id === id);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find(category => category.id === id);
}